/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

synchronized public void win_draw1(PApplet appc, GWinData data) { //_CODE_:window2:991702:
  appc.background(230);
} //_CODE_:window2:991702:

public void compDropDownSelected(GDropList source, GEvent event) { //_CODE_:compDropDown:776360:
  chosenComp = compDropDown.getSelectedIndex();
} //_CODE_:compDropDown:776360:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("Sketch Window");
  window2 = GWindow.getWindow(this, "Window title", 0, 0, 240, 120, JAVA2D);
  window2.noLoop();
  window2.setActionOnClose(G4P.KEEP_OPEN);
  window2.addDrawHandler(this, "win_draw1");
  compDropDown = new GDropList(window2, 48, 20, 140, 80, 3, 10);
  compDropDown.setItems(loadStrings("list_776360"), 0);
  compDropDown.setLocalColorScheme(GCScheme.PURPLE_SCHEME);
  compDropDown.addEventHandler(this, "compDropDownSelected");
  window2.loop();
}

// Variable declarations 
// autogenerated do not edit
GWindow window2;
GDropList compDropDown; 
