/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

synchronized public void win_draw2(PApplet appc, GWinData data) { //_CODE_:window3:407295:
  appc.background(230);
} //_CODE_:window3:407295:

public void compDropListSelected(GDropList source, GEvent event) { //_CODE_:compDropList:419589:
  chosenComp = compDropList.getSelectedIndex();
} //_CODE_:compDropList:419589:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("Sketch Window");
  window3 = GWindow.getWindow(this, "Window title", 0, 0, 240, 120, JAVA2D);
  window3.noLoop();
  window3.setActionOnClose(G4P.KEEP_OPEN);
  window3.addDrawHandler(this, "win_draw2");
  compDropList = new GDropList(window3, 48, 20, 140, 80, 3, 10);
  compDropList.setItems(loadStrings("list_419589"), 0);
  compDropList.setLocalColorScheme(GCScheme.PURPLE_SCHEME);
  compDropList.addEventHandler(this, "compDropListSelected");
  window3.loop();
}

// Variable declarations 
// autogenerated do not edit
GWindow window3;
GDropList compDropList; 
